version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      
  document-service:
    build: .
    command: bin/puma config.ru -p 3000
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
